sudo: required
services:
  - docker

before_install:
  - docker build -t vuphong95663/learn-ops -f Dockerfile.dev .

script:
  - docker run vuphong95663/learn-ops npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "ops-sample"
  env: "OpsSample-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-170139420953"
  bucket_path: "learn-ops"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
